// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CLIStatus() {
  return window['go']['main']['App']['CLIStatus']();
}

export function InstallCLI() {
  return window['go']['main']['App']['InstallCLI']();
}

export function NearbyServers() {
  return window['go']['main']['App']['NearbyServers']();
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
