// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CLIStatus():Promise<Record<string, any>>;

export function InstallCLI():Promise<Record<string, any>>;

export function NearbyServers():Promise<Array<main.Server>>;

export function Run(arg1:Array<number>):Promise<void>;

export function Stop():Promise<void>;
